[config]
version_check = false

[templates.quickshell]
input_path = "templates/quickshell-colors.json"
output_path = "~/.cache/quickshell-dev-colorscheme/colors.json"

[templates.btop]
input_path = "templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"
post_hook = "pkill -USR2 btop >/dev/null 2>&1 || true"

[templates.cava]
input_path = "templates/cava-colors.ini"
output_path = "~/.config/cava/themes/matugen"
post_hook = "pkill -USR1 cava >/dev/null 2>&1 || true"

[templates.kitty]
input_path = "templates/kitty-colors.conf"
output_path = "~/.config/kitty/themes/Matugen.conf"
post_hook = "cp \"$HOME/.config/kitty/themes/Matugen.conf\" \"$HOME/.config/kitty/current-theme.conf\" && (pkill -USR1 -x kitty >/dev/null 2>&1 || true)"

[templates.fcitx5]
input_path = "templates/fcitx5-theme.conf"
output_path = "~/.local/share/fcitx5/themes/Matugen/theme.conf"
post_hook = "busctl --user call org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1 ReloadAddonConfig s classicui >/dev/null 2>&1 || true"

[templates.niri]
input_path = "templates/niri-colors.kdl"
output_path = "~/.config/niri/colors.kdl"
post_hook = "niri msg action load-config-file >/dev/null 2>&1 || true"

[templates.yazi]
input_path = "templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.zsh_prompt]
input_path = "templates/zsh-prompt-colors.zsh"
output_path = "~/.cache/quickshell-dev-colorscheme/zsh-prompt-colors.zsh"

[templates.fcitx5_panel_svg]
input_path = "templates/fcitx5-panel.svg"
output_path = "~/.local/share/fcitx5/themes/Matugen/panel.svg"

[templates.fcitx5_highlight_svg]
input_path = "templates/fcitx5-highlight.svg"
output_path = "~/.local/share/fcitx5/themes/Matugen/highlight.svg"
